# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

modGroup=com.ldtteam
modVersion=0.0.1
modId=multipiston
modBaseName=multipiston

forgeVersion=21.0.148
minecraftVersion=1.21
exactMinecraftVersion=1.21
additionalMinecraftVersions=

blockUiVersion=1.21-1.0.160-BETA
domumOrnamentumVersion=1.21-1.0.195-BETA
structurize_version=1.0.743-BETA

mappingsChannel=official
mappingsVersion=1.20

requiredCurseDependencies=blockui

githubUrl=
gitUrl=
gitConnectUrl=
projectUrl=

curseId=303278
usesCurse=true

usesOptifine=false
useDefaultTestSystem=false
runtimeSourceSets=main
projectHasApi=false
primaryJarClassifier=
isFMLLibrary=false
usesResourceDataExpansionFromProjectKeys=false

javaVersion=21
useJavaToolChains=true

